### ISSUE TITLE
Reading in eccentricity expansion coefficients

### ISSUE THREAD

**Issue by jxcbecker** [kpenev/poet#57]
Hello Kaloyan - 

Thanks for building this code and making it available to the community! 

I was wondering about reading in the file containing the eccentricity expansion coefficients. In the documentation here: https://kpenev.github.io/poet/python_orbital_evolution.html , it says to use: 

```
from orbital_evolution.evolve_interface import library as\
orbital_evolution_library

orbital_evolution_library.read_eccentricity_expansion_coefficients(    <filename with eccentricity expansion coefficients>)
```

Is this the correct method to read in the coefficients with the current version of the code (which has been updated quite a lot since that documentation was written, it appears)? For me, Python cannot locate the function (```AttributeError: dlsym(0x308f35730, read_eccentricity_expansion_coefficients): symbol not found```. While I think my build worked correctly, I think this either indicates that it didn't link correctly, or the name of that method has been updated - so wanted to check that it wasn't the latter before I get too much deeper into debugging.

Thanks!

Juliette Becker

**Comment by Vortebo** [comment]
Hello,

Sorry about that, the documentation is indeed somewhat out of date! The function you want is `orbital_evolution_library.prepare_eccentricity_expansion(filename, precision, pre_load, disable_precision_fail)`,
where filename is an ascii-encoded string, precision is a double (e.g. `1e-4`), and pre_load and disable_precision_fail are bools.

You've probably also noticed that the file this function is meant to read isn't actually in the repository; this is because it's over 9 gigabytes large. We provide the scripts to generate it in the scripts folder (`autorun.py` is what one would mainly be interacting with to recreate the file), but if I'm not mistaken there are one or two expansions that get duplicated which need to be removed manually after the fact, and the scripts as a whole are probably somewhat less-than-user friendly. If you'd like, we can find a way to send you our generated file (over Google Drive or Box or something similar).

Regards,
Joshua Schussler

**Comment by jxcbecker** [comment]
Ah, wonderful, thank you for the information - I see that method now!

I did find the scripts, but did not know about the need to remove some rows - I would certainly appreciate the working file!  I will send you an email. 

I really appreciate the help, thanks again!
